// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: xerr/proto/xerr.proto

package xerr

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reason int32

const (
	// 鉴权错误包括:token错误、token过期、token无效、无权限访问等
	Reason_AUTH Reason = 0
	// 数据操作错误包括:数据不存在、数据已存在、数据已删除等
	Reason_DB_OPTION Reason = 4
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0: "AUTH",
		4: "DB_OPTION",
	}
	Reason_value = map[string]int32{
		"AUTH":      0,
		"DB_OPTION": 4,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_xerr_proto_xerr_proto_enumTypes[0].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_xerr_proto_xerr_proto_enumTypes[0]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_xerr_proto_xerr_proto_rawDescGZIP(), []int{0}
}

var File_xerr_proto_xerr_proto protoreflect.FileDescriptor

var file_xerr_proto_xerr_proto_rawDesc = []byte{
	0x0a, 0x15, 0x78, 0x65, 0x72, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x78, 0x65, 0x72,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x78, 0x65, 0x72, 0x72, 0x2e, 0x76, 0x31,
	0x1a, 0x13, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x33, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x04, 0x41, 0x55, 0x54, 0x48, 0x10, 0x00, 0x1a, 0x04, 0xa8, 0x45, 0x91, 0x03, 0x12,
	0x13, 0x0a, 0x09, 0x44, 0x42, 0x5f, 0x4f, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x1a, 0x04,
	0xa8, 0x45, 0x93, 0x03, 0x1a, 0x04, 0xa0, 0x45, 0xf4, 0x03, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x78, 0x65, 0x72, 0x72, 0x3b, 0x78, 0x65, 0x72, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xerr_proto_xerr_proto_rawDescOnce sync.Once
	file_xerr_proto_xerr_proto_rawDescData = file_xerr_proto_xerr_proto_rawDesc
)

func file_xerr_proto_xerr_proto_rawDescGZIP() []byte {
	file_xerr_proto_xerr_proto_rawDescOnce.Do(func() {
		file_xerr_proto_xerr_proto_rawDescData = protoimpl.X.CompressGZIP(file_xerr_proto_xerr_proto_rawDescData)
	})
	return file_xerr_proto_xerr_proto_rawDescData
}

var file_xerr_proto_xerr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xerr_proto_xerr_proto_goTypes = []interface{}{
	(Reason)(0), // 0: xerr.v1.Reason
}
var file_xerr_proto_xerr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xerr_proto_xerr_proto_init() }
func file_xerr_proto_xerr_proto_init() {
	if File_xerr_proto_xerr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xerr_proto_xerr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xerr_proto_xerr_proto_goTypes,
		DependencyIndexes: file_xerr_proto_xerr_proto_depIdxs,
		EnumInfos:         file_xerr_proto_xerr_proto_enumTypes,
	}.Build()
	File_xerr_proto_xerr_proto = out.File
	file_xerr_proto_xerr_proto_rawDesc = nil
	file_xerr_proto_xerr_proto_goTypes = nil
	file_xerr_proto_xerr_proto_depIdxs = nil
}
